name : Deploy Laravel Project to Hostinger

on :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, xml, curl, zip, bcmath
          ini-values:
            display_errors = On
            error_reporting = E_ALL

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Optimize Application
        run: php artisan optimize:clear

      - name: Deploy to Hostinger
        run: ${{ secrets.SSH_ACCESS }}

      - name : Input Password for Hostinger
        run: echo "${{ secrets.SSH_PASSWORD }}" | sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no -T user@hostinger.com

