name : Deploy Laravel Project to Hostinger

on :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, xml, curl, zip, bcmath
          ini-values:
            display_errors = On
            error_reporting = E_ALL


      - name: "nodejs"
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: "npm"
        run: npm install

      - name: "npm run build"
        run: npm run build

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      - name: environment variables
        run: cp .env.example .env


      - name: Generate Application Key
        run: php artisan key:generate

      - name: Migrate Database
        run: php artisan migrate --force

      - name: Optimize Application
        run: php artisan optimize:clear

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          remote-dir: /public_html/fms/

          state-name: .git-ftp-state
          exclude: |                  # ✅ Corrected formatting from a sequence to a multi-line string
            **/.git*
            **/.git*/**
            **/node_modules/**




